# Generated by Django 5.2.13 on 2026-04-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100, unique=True, verbose_name='项目唯一ID')),
                ('sheet_row_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sheet行ID')),
                ('program_name', models.CharField(max_length=255, verbose_name='专业名称')),
                ('module_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='模块名称')),
                ('course_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='课程名称')),
                ('semester', models.CharField(blank=True, max_length=50, null=True, verbose_name='学期')),
                ('title_zh', models.CharField(max_length=255, verbose_name='项目名称（中文）')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='项目名称（英文）')),
                ('background', models.CharField(blank=True, max_length=255, null=True, verbose_name='项目背景')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='作品简介')),
                ('features', models.TextField(blank=True, null=True, verbose_name='作品特色')),
                ('students', models.TextField(blank=True, null=True, verbose_name='学生名字')),
                ('teachers', models.CharField(blank=True, max_length=255, null=True, verbose_name='指导老师')),
                ('poster_image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='海报图URL')),
                ('thumbnail_image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='封面缩略图URL')),
                ('youtube_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='YouTube链接')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='标签')),
                ('is_featured', models.BooleanField(default=False, verbose_name='首页推荐')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序值')),
                ('sync_source', models.CharField(default='google_sheet', max_length=50, verbose_name='同步来源')),
                ('sync_status', models.CharField(default='synced', max_length=50, verbose_name='同步状态')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='后台备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '展示项目',
                'verbose_name_plural': '展示项目',
                'db_table': 'showcase_projects',
                'ordering': ['sort_order', '-id'],
            },
        ),
    ]
