# Generated by Django 5.2.13 on 2026-04-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showcaseproject',
            options={'ordering': ['-academic_year', 'sort_order', '-id'], 'verbose_name': '展示项目', 'verbose_name_plural': '展示项目'},
        ),
        migrations.AddField(
            model_name='showcaseproject',
            name='academic_year',
            field=models.IntegerField(default=2025, verbose_name='评选学年'),
        ),
        migrations.AddField(
            model_name='showcaseproject',
            name='award_level',
            field=models.IntegerField(blank=True, choices=[(1, '一等奖'), (2, '二等奖'), (3, '三等奖'), (4, '优秀奖')], null=True, verbose_name='奖项等级'),
        ),
    ]
