# Generated by Django 5.2.13 on 2026-04-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0002_alter_showcaseproject_options_and_more"),
    ]

    operations = [
        # 重命名字段 - 保留数据
        migrations.RenameField(
            model_name="showcaseproject",
            old_name="title_en",
            new_name="project_title_en",
        ),
        migrations.RenameField(
            model_name="showcaseproject",
            old_name="title_zh",
            new_name="project_title_cn",
        ),
        migrations.RenameField(
            model_name="showcaseproject",
            old_name="program_name",
            new_name="major",
        ),
        migrations.RenameField(
            model_name="showcaseproject",
            old_name="background",
            new_name="project_intro",
        ),
        migrations.RenameField(
            model_name="showcaseproject",
            old_name="description",
            new_name="project_description",
        ),
        migrations.RenameField(
            model_name="showcaseproject",
            old_name="poster_image_url",
            new_name="poster_url",
        ),
        migrations.RenameField(
            model_name="showcaseproject",
            old_name="thumbnail_image_url",
            new_name="thumbnail_url",
        ),
        # 注意：sheet_row_id (CharField) 不能直接重命名为 IntegerField
        # 先删除旧字段，再添加新字段
        migrations.RemoveField(
            model_name="showcaseproject",
            name="sheet_row_id",
        ),
        # 删除旧字段
        migrations.RemoveField(
            model_name="showcaseproject",
            name="course_name",
        ),
        migrations.RemoveField(
            model_name="showcaseproject",
            name="last_synced_at",
        ),
        migrations.RemoveField(
            model_name="showcaseproject",
            name="module_name",
        ),
        migrations.RemoveField(
            model_name="showcaseproject",
            name="sync_source",
        ),
        migrations.RemoveField(
            model_name="showcaseproject",
            name="teachers",
        ),
        # 新增 google_sheet_row_number 字段（替代已删除的 sheet_row_id）
        migrations.AddField(
            model_name="showcaseproject",
            name="google_sheet_row_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Google Sheet行号"
            ),
        ),
        # 修改字段类型（RenameField 后修改类型）
        migrations.AlterField(
            model_name="showcaseproject",
            name="major",
            field=models.CharField(default="", max_length=100, verbose_name="专业名称"),
        ),
        migrations.AlterField(
            model_name="showcaseproject",
            name="poster_url",
            field=models.TextField(blank=True, null=True, verbose_name="海报图URL"),
        ),
        migrations.AlterField(
            model_name="showcaseproject",
            name="project_description",
            field=models.TextField(blank=True, null=True, verbose_name="作品简介"),
        ),
        migrations.AlterField(
            model_name="showcaseproject",
            name="project_intro",
            field=models.TextField(blank=True, null=True, verbose_name="项目背景"),
        ),
        migrations.AlterField(
            model_name="showcaseproject",
            name="project_title_cn",
            field=models.CharField(
                default="", max_length=255, verbose_name="项目名称（中文）"
            ),
        ),
        migrations.AlterField(
            model_name="showcaseproject",
            name="thumbnail_url",
            field=models.TextField(blank=True, null=True, verbose_name="封面缩略图URL"),
        ),
        # 新增字段
        migrations.AddField(
            model_name="showcaseproject",
            name="ca_course",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="CA课程"
            ),
        ),
        migrations.AddField(
            model_name="showcaseproject",
            name="ca_instructors",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="CA教师"
            ),
        ),
        migrations.AddField(
            model_name="showcaseproject",
            name="cd_course",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="CD课程"
            ),
        ),
        migrations.AddField(
            model_name="showcaseproject",
            name="cd_instructors",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="CD教师"
            ),
        ),
        migrations.AddField(
            model_name="showcaseproject",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="联系邮箱"
            ),
        ),
        migrations.AddField(
            model_name="showcaseproject",
            name="fa_course",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="FA课程"
            ),
        ),
        migrations.AddField(
            model_name="showcaseproject",
            name="fa_instructors",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="FA教师"
            ),
        ),
        migrations.AddField(
            model_name="showcaseproject",
            name="ge_course",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="GE课程"
            ),
        ),
        migrations.AddField(
            model_name="showcaseproject",
            name="ge_instructors",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="GE教师"
            ),
        ),
        migrations.AddField(
            model_name="showcaseproject",
            name="ib_course",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="IB课程"
            ),
        ),
        migrations.AddField(
            model_name="showcaseproject",
            name="ib_instructors",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="IB教师"
            ),
        ),
        migrations.AddField(
            model_name="showcaseproject",
            name="poster_file_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="海报文件ID"
            ),
        ),
        migrations.AddField(
            model_name="showcaseproject",
            name="poster_file_url",
            field=models.TextField(blank=True, null=True, verbose_name="海报文件URL"),
        ),
        migrations.AddField(
            model_name="showcaseproject",
            name="submit_timestamp",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="提交时间"
            ),
        ),
        migrations.AddField(
            model_name="showcaseproject",
            name="thumbnail_file_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="缩略图文件ID"
            ),
        ),
        migrations.AddField(
            model_name="showcaseproject",
            name="thumbnail_file_url",
            field=models.TextField(blank=True, null=True, verbose_name="缩略图文件URL"),
        ),
        migrations.AddField(
            model_name="showcaseproject",
            name="tm_course",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="TM课程"
            ),
        ),
        migrations.AddField(
            model_name="showcaseproject",
            name="tm_instructors",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="TM教师"
            ),
        ),
    ]
