# Generated by Django 5.2.13 on 2026-04-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_rename_title_en_showcaseproject_project_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcaseproject',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='showcaseproject',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
